# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfproviderdocs < Formula
  desc "Terraform Provider Documentation Tool"
  homepage "https://github.com/YakDriver/tfproviderdocs"
  version "0.18.0"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/YakDriver/tfproviderdocs/releases/download/v0.18.0/tfproviderdocs_0.18.0_darwin_amd64.tar.gz"
      sha256 "0c2931adb789207e2d4fc2566ba55d088c8fd7245692fe594d7fc62e930db7a2"

      def install
        bin.install "tfproviderdocs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/YakDriver/tfproviderdocs/releases/download/v0.18.0/tfproviderdocs_0.18.0_darwin_arm64.tar.gz"
      sha256 "1844ebfbe9b92119eb11bb12cd023936446de5a55e4b69b850a2dfe29baba9f1"

      def install
        bin.install "tfproviderdocs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/YakDriver/tfproviderdocs/releases/download/v0.18.0/tfproviderdocs_0.18.0_linux_amd64.tar.gz"
      sha256 "ab95080bdeb39d15363a5ad61bc0273b98aa058eac785d19395fdeb548b518d5"
      def install
        bin.install "tfproviderdocs"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/YakDriver/tfproviderdocs/releases/download/v0.18.0/tfproviderdocs_0.18.0_linux_arm64.tar.gz"
      sha256 "cc0c807e0bd767e00ed8949148a69e72b62139940ef1fa93dd5710c2e62ecd79"
      def install
        bin.install "tfproviderdocs"
      end
    end
  end

  test do
    system "#{bin}/tfproviderdocs -v"
  end
end
