name: Update Terraform Formulas

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Specify the Ruby version you need

      - name: Install dependencies
        run: |
          gem install nokogiri

      - name: Run update script
        run: |
          ruby update_terraform_latest_beta.rb
          ruby update_terraform_latest_alpha.rb
          ruby update_terraform.rb

      - name: Env versions
        id: env_version
        run: |
          echo "LATEST_ALPHA_VERSION=$(cat terraform_latest_alpha_version.txt)" >> $GITHUB_ENV  
          echo "LATEST_BETA_VERSION=$(cat terraform_latest_beta_version.txt)" >> $GITHUB_ENV
          echo "LATEST_VERSION=$(cat terraform_latest_version.txt)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          committer: yakdriverbot <f1formula.juan@gmail.com>
          author: yakdriverbot <f1formula.juan@gmail.com>
          commit-message: "Update Terraform formulas to alpha/beta/stable versions ${{ env.LATEST_ALPHA_VERSION }}/${{ env.LATEST_BETA_VERSION }}/${{ env.LATEST_VERSION }}"
          base: main
          branch: update-terraform-formulas
          title: "Update Terraform formulas to alpha/beta/stable versions ${{ env.LATEST_ALPHA_VERSION }}/${{ env.LATEST_BETA_VERSION }}/${{ env.LATEST_VERSION }}"
          body: "This PR updates the Terraform formulas to alpha/beta/stable versions ${{ env.LATEST_ALPHA_VERSION }}/${{ env.LATEST_BETA_VERSION }}/${{ env.LATEST_VERSION }} with the latest sha256 hashes."
