name: Update Formulas

on:
  schedule:
    - cron: '0 5,17 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  pull-requests: write

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install nokogiri

      - name: Run update script
        run: |
          ruby update.rb

      - name: Read update summary
        id: read_summary
        run: |
          echo "UPDATE_SUMMARY<<EOF" >> $GITHUB_ENV
          cat update_summary.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GH_PAT }}
          committer: yakdriverbot <f1formula.juan@gmail.com>
          author: yakdriverbot <f1formula.juan@gmail.com>
          commit-message: "Update formulas"
          base: main
          branch: update-formulas
          title: "Update formulas"
          body: |
            This PR updates the following formulas with the latest versions and sha256 hashes:

            ${{ env.UPDATE_SUMMARY }}
