name: Update Terraform Beta Formula

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Specify the Ruby version you need

      - name: Install dependencies
        run: |
          gem install nokogiri

      - name: Run update script
        run: ruby update_terraform-latest-beta.rb

      - name: Commit and push changes
        run: |
          git config --global user.name 'yakdriverbot'
          git config --global user.email 'f1formula.juan@gmail.com'
          git add terraform-latest-beta.rb
          git commit -m 'Update Terraform beta formula to version ${latest_beta_version}'
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Terraform beta formula to version ${latest_beta_version}
          branch: update-terraform-beta-formula
          title: Update Terraform beta formula to version ${latest_beta_version}
          body: This PR updates the Terraform beta formula to version ${latest_beta_version} with the latest sha256 hashes.
